name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build code
        run: npm run build

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker auth
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and push Docker image
        run: gcloud builds submit --tag us-central1-docker.pkg.dev/autolinks-489416/autolinks-repo/autolinks:latest .

      - name: Run migrations
        run: npm run db:migrate

      - name: Deploy to Cloud Run
        run: gcloud run deploy autolinks --image us-central1-docker.pkg.dev/autolinks-489416/autolinks-repo/autolinks:latest --region us-central1 --allow-unauthenticated --project autolinks-489416 --max-instances=4 --set-env-vars DATABASE_URL=${{ secrets.DATABASE_URL }},JWT_SECRET=${{ secrets.JWT_SECRET }}
